### ISSUE TITLE
Using with replay mod

### ISSUE THREAD

**Issue by ghost** [thatDudo/Omniscience-Fabric#4]
Hello, would it be possible for this to work with replay mod?

**Comment by thatDudo** [comment]
Yes, I have looked into it and it would seem ReplayMod hinders the rendering of invisible entities entirely, thereby hindering the mod from drawing the transparent models. I will add an option to force render entity models in the next version of Omniscience for 1.18 and 1.19. If you need support for older versions of Minecraft feel free to open a new Issue!
