### ISSUE TITLE
Minecraft crashes after pressing the "settings" keybind

### ISSUE THREAD

**Issue by Whitelisted1** [thatDudo/Omniscience-Fabric#5]
When attempting to open the settings menu with the keybind, the game crashes and gives the following error:
```
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void net.minecraft.class_4185.<init>(int, int, int, int, net.minecraft.class_2561, net.minecraft.class_4185$class_4241)'
```
Version: 1.19.4
Fabric API Version 0.83.0

This occurs even without any other mods installed (other than fabric API)

**Comment by thatDudo** [comment]
The cloth config version was outdated it seems. I have updated it and created a new version, Thanks for your help!
